name: Check shuttle
on:
  schedule:
    - cron: "55 18 * * *" 
defaults:
 run:
  working-directory: Manga
  shell: bash

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Runs a set of commands using the runners shell
      - name: Run Something
        run: |
          scrapy crawl Manganelo -o Last.csv
